### ISSUE TITLE
Handle no-raffle case correctly.

### ISSUE THREAD

**Issue by ewlsh** [Get-Your-GreenBack-Tompkins/gygb-client-web#33]
When the get raffle endpoint sends a 404 error, the frontend should still function normally - omitting information about the raffle.

**Comment by ewlsh** [comment]
Addressed in #39.

**Comment by ashneeldas2** [comment]
If there is no raffle, the loading bar remains there permanently on the result page.

**Comment by ewlsh** [comment]
Fixed in #39.
