### ISSUE TITLE
Client tutorial information

### ISSUE THREAD

**Issue by ashneeldas2** [Get-Your-GreenBack-Tompkins/gygb-client-web#4]
Todo

- [X] Create new component(s) for the tutorial
- [X] Determine the content for the tutorial
- ~Include privacy policy~ (punted to future issue)
- [X] Make content dynamic (depends on backend)

Acceptance Criteria

- [X] Tutorial is displayed upon opening app
- ~Can accept privacy policy~ (punted to future issue)
- [X] Content is pulled from backend

Skeleton:
 ```json
{
    "header": "welcome to the quiz",
    "body": "hello and good day sir, welcome to thee quiz",
    "successMetrics": {
        "total": 5,
        "successLevel": 4
    },
    "prize": "Lux Thermostat 5000"
}
```

**Comment by ewlsh** [comment]
@rockon999 terms and condition retrieval is blocked on adding TOS API.

@jw792 switch to using raffle API. (a GET to `/quiz/web-client/raffle`)

**Comment by ewlsh** [comment]
Addressed, punting privacy policy work to future issue.
